# Generated by Django 5.0.9 on 2024-12-07 12:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('current_charge', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'phone_numbers',
                'indexes': [models.Index(fields=['number'], name='phone_numbe_number_ce8d4d_idx'), models.Index(fields=['is_active'], name='phone_numbe_is_acti_eb40ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='CreditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('processed', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credit_requests',
                'indexes': [models.Index(fields=['user', 'created_at'], name='credit_requ_user_id_e1446d_idx'), models.Index(fields=['status'], name='credit_requ_status_f2488a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChargeSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('processed', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_response', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='charge.phonenumber')),
            ],
            options={
                'db_table': 'charge_sales',
                'indexes': [models.Index(fields=['user', 'created_at'], name='charge_sale_user_id_836a8c_idx'), models.Index(fields=['phone_number'], name='charge_sale_phone_n_555563_idx'), models.Index(fields=['status'], name='charge_sale_status_b0f433_idx')],
            },
        ),
    ]
