# Generated by Django 5.0.9 on 2024-12-08 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chargesale',
            constraint=models.UniqueConstraint(condition=models.Q(('processed', True)), fields=('id', 'processed'), name='unique_processed_request'),
        ),
    ]
