# Generated by Django 5.0.9 on 2024-12-10 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0003_chargesale_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargesale',
            name='seller',
        ),
    ]
